### ISSUE TITLE
Can't build model in alexa developer console

### ISSUE THREAD

**Issue by NikhilKanamarla** [3SpheresRoboticsProject/flask_ask_ros#2]
Original error: Build Failed
There are missing slot values in slot type "AMAZON.FirstName" for slot "name" in intent "TestIntent". Error code: MissingSlot

After adding a slot value: Build Failed
Slot type name "AMAZON.FirstName" is invalid. The name of a custom slot type must begin with an alphabetic character and can consist only of alphabetic characters or underscores. Error code: InvalidSlotTypeName

**Comment by LucasPorto** [comment]
Hi,

AMAZON.FirstName is a built-in slot for the English (US) language.

What language is your skill in?

**Comment by NikhilKanamarla** [comment]
I fixed it no worries, check my other comment

**Comment by nishantpant** [comment]
"I fixed it no worries"...where is your other comment? I have the same issue

**Comment by LucasPorto** [comment]
Hi, what language is your skill in?

You may want to replace the slot "AMAZON.FirstName" by an equivalent slot depending on your language.

See: https://developer.amazon.com/docs/custom-skills/slot-type-reference.html#list-slot-types
